
export const LOGGED_IN_SUCCESS = "LOGGED_IN_SUCCESS"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const LOGGED_OUT_SUCCESS = "LOGGED_OUT_SUCCESS"
export const FETCH_QUEUE_SUCCESS = "FETCH_QUEUE_SUCCESS"
export const FETCH_ARCHIVE_SUCCESS = "FETCH_ARCHIVE_SUCCESS"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const POST_QUESTION = "POST_QUESTION"
export const POST_ANSWER = "POST_ANSWER"
export const UPDATE_QUESTION = "UPDATE_QUESTION"
export const UPDATE_ANSWER = "UPDATE_ANSWER"
export const TOGGLE_SHOW_ANSWERS = "TOGGLE_SHOW_ANSWER"

